version: '3.3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - stack
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 1700M
#        reservations:
#          cpus: '0.25'
#          memory: 500M

  kibana:
    image: docker.elastic.co/kibana/kibana:$KIBABA_VERSION
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
      - logstash
    links:
      - elasticsearch
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "demo_kibana"
    networks:
      - stack
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 600M
#        reservations:
#          cpus: '0.25'
#          memory: 200M

  logstash:
    image: docker.elastic.co/logstash/logstash:$LOGSTASH_VERSION
    links:
      - elasticsearch
    volumes:
      - .:/etc/logstash
    command: logstash -f /etc/logstash/logstash.conf
    ports:
      - 12201:12201/udp
    depends_on:
      - elasticsearch
    networks:
      - stack
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 600M
#        reservations:
#          cpus: '0.25'
#          memory: 200M

networks:
  stack: {}
